
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/navbar/Navbar";
import Footer from "@/components/shared/Footer";
import ToastProvider from "@/components/shared/ToastProvider";


const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en" data-theme="light"
      className={`${inter.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col ">
        <Navbar />
        <main className="min-h-screen  my-10  ">
          {children}
        </main>
        <Footer />
        <ToastProvider />
      </body>
    </html>
  );
}
